---
title: "Harnessing Data from North Carolina's Jails to Inform Effective Policies — California Jail Profile Survey"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
library(here)
library(shiny)
```

```{r data}
options(scipen = 999)

county_m <- read.csv(here("data", "california_jail_county_monthly_1995_2020.csv"))
county_m$date <- as.Date(county_m$date, format = "%Y-%m-%d")
county_m$day_of_highest_count <- as.Date(county_m$day_of_highest_count, format = "%Y-%m-%d")
county_m <- county_m %>% 
  rename(unsen_male = avg_daily_pop_unsentenced_male, unsen_female = avg_daily_pop_unsentenced_female,
         sen_male = avg_daily_pop_sentenced_male, sen_female = avg_daily_pop_sentenced_female,
         total = avg_daily_pop_total_jurisdiction, felony_unsen = avg_felony_inmate_unsentenced,
         felony_sen = avg_felony_inmate_sentenced, felony_total = avg_felony_inmate_total,
         misd_unsen = avg_misdemean_inmate_unsentenced, misd_sen = avg_misdemean_inmate_sentenced,
         misd_total = avg_misdemean_inmate_total, county = census_county_name) %>% 
  select(4, 5, 9:19, 22:41)

county_q <- read.csv(here("data", "california_jail_county_quarterly_1995_2020.csv"))
county_q$quarter <- as.factor(county_q$quarter)
county_q <- county_q %>% 
  rename(county = census_county_name, pretrial_release = avg_length_stay_pretrial_release, 
         sentenced_release = avg_length_stay_sentnced_release) %>% 
  mutate(month = case_when(quarter == 1 ~ 1, quarter == 2 ~ 4, quarter == 3 ~ 7, quarter == 4 ~ 10),
         date = as.Date(ISOdate(year, month, "01")))

facility <- read.csv(here("data", "california_jail_facility_monthly_1995_2020.csv"))
facility$date <- as.Date(facility$date, format = "%Y-%m-%d")
facility <- facility %>% 
  rename(unsen_male = avg_daily_pop_unsentenced_male, unsen_female = avg_daily_pop_unsentenced_female, 
         sen_male = avg_daily_pop_sentenced_male, sen_female = avg_daily_pop_sentenced_female,
         total = avg_daily_pop_total_facility, county = census_county_name)
```

# To Do
* total / capacity of facility
* did jails expand to accomodate population increases? correlation w/ urban/rural?

# Population

```{r population_data}
# sum populations by county & date
population <- county_m %>% 
  select(county, date, unsen_male, unsen_female, sen_male, sen_female, total) %>% 
  group_by(county, date) %>% 
  mutate(unsen_male = sum(unsen_male), unsen_female = sum(unsen_female),
         sen_male = sum(sen_male), sen_female = sum(sen_female), total = sum(total)) %>% 
  unique() %>% 
  group_by(county) %>% 
  arrange(date, .by_group = TRUE)
```

```{r population_analysis}
# calculate changes in population 1, 3, and 5 years after realignment
population_one_yr <- county_m %>% 
  filter(year(date) == 2011 | year(date) == 2012, month(date) == 1) %>%
  select(date, county, total) %>% 
  arrange(date) %>% 
  group_by(county, date) %>%
  mutate(total = sum(total)) %>% 
  unique() %>% 
  group_by(county) %>% 
  mutate(change = (total / lag(total) - 1) * 100) %>% 
  filter(year(date) == 2012)

population_three_yr <- county_m %>% 
  filter(year(date) == 2011 | year(date) == 2014, month(date) == 1) %>%
  select(date, county, total) %>% 
  arrange(date) %>% 
  group_by(county, date) %>%
  mutate(total = sum(total)) %>% 
  unique() %>% 
  group_by(county) %>% 
  mutate(change = (total / lag(total) - 1) * 100) %>% 
  filter(year(date) == 2014)

population_five_yr <- county_m %>% 
  filter(year(date) == 2011 | year(date) == 2016, month(date) == 1) %>%
  select(date, county, total) %>% 
  arrange(date) %>% 
  group_by(county, date) %>%
  mutate(total = sum(total)) %>% 
  unique() %>% 
  group_by(county) %>% 
  mutate(change = (total / lag(total) - 1) * 100) %>% 
  filter(year(date) == 2016)

population_five_yr[nrow(population_five_yr) + 1,] = list(as.Date("2016-01-01"), "Sierra County", 0, 0)

population_five_yr <- population_five_yr %>% 
  arrange(county)

realignment_population <- county_m %>% 
  filter(year(date) == 2011 & month(date) == 1) %>% 
  select(county, total) %>% 
  group_by(county) %>% 
  mutate(total = sum(total)) %>% 
  unique() %>% 
  rename(`2011_total` = total)

realignment_population$`2012_total` = population_one_yr$total
realignment_population$`2012_change` = population_one_yr$change
realignment_population$`2014_total` = population_three_yr$total
realignment_population$`2014_change` = population_three_yr$change
realignment_population$`2016_total` = population_five_yr$total
realignment_population$`2016_change` = population_five_yr$change

quantile(realignment_population$`2012_change`, c(0.25, 0.5, 0.75))
quantile(realignment_population$`2014_change`, c(0.25, 0.5, 0.75))
quantile(realignment_population$`2016_change`, c(0.25, 0.5, 0.75))

realignment_population %>% 
  filter(`2012_change` < -4.368030 | `2014_change` <  4.295704 | `2014_change` < -6.459330)
realignment_population %>% 
  filter(`2012_change` < -4.368030 & `2014_change` <  4.295704 & `2014_change` < -6.459330)

realignment_population %>% 
  filter(`2012_change` > 8.823529 | `2014_change` > 24.584718 | `2016_change` > 19.323671)
realignment_population %>% 
  filter(`2012_change` > 8.823529 & `2014_change` > 24.584718 & `2016_change` > 19.323671)

# calculate ratio of unsentenced:sentenced
population %>% 
  mutate(unsen = unsen_male + unsen_female, sen = sen_male + sen_female, ratio = unsen / sen) %>% 
  select(county, date, unsen, sen, ratio) %>% 
  group_by(year(date)) %>% 
  summarize(q25 = quantile(ratio, 0.25, na.rm = TRUE), median = median(ratio, na.rm = TRUE),
            q75 = quantile(ratio, 0.75, na.rm = TRUE))
```

```{r population_modeling}
total_model <- lm(total~factor(county) + date, data = population)
summary(total_model)
unsen_male_model <- lm(unsen_male~factor(county) + date, data = population)
summary(unsen_male_model)
unsen_female_model <- lm(unsen_female~factor(county) + date, data = population)
summary(unsen_female_model)
sen_male_model <- lm(sen_male~factor(county) + date, data = population)
summary(sen_male_model)
sen_female_model <- lm(sen_female~factor(county) + date, data = population)
summary(sen_female_model)
```

```{r population_viz}
county_m %>% 
  select(date, unsen_male, unsen_female, sen_male, sen_female, total) %>% 
  group_by(date) %>% 
  mutate(unsen_male = sum(unsen_male), unsen_female = sum(unsen_female),
         sen_male = sum(sen_male), sen_female = sum(sen_female), total = sum(total)) %>% 
  unique() %>% 
  arrange(date) %>% 
  ggplot(data = ., mapping = aes(x = date, group = 1)) +
  geom_line(mapping = aes(y = sen_male, color = "male", linetype = "solid")) +
  geom_line(mapping = aes(y = sen_female, color = "female", linetype = "solid")) +
  geom_line(mapping = aes(y = unsen_male, color = "male", linetype = "dotted")) +
  geom_line(mapping = aes(y = unsen_female, color = "female", linetype = "dotted")) +
  labs(x = "Year", y = "Average Daily Populations") +
  scale_color_discrete(name = "Gender", breaks = c("male", "female"), labels = c("Male", "Female")) +
  scale_linetype_manual(name = "Sentence Type",
                        values = c("solid", "dotted"), labels = c("Sentenced", "Unsentenced")) +
  theme_classic() +
  theme(axis.text.x = element_text(color = "#000000", size = 10),
        axis.text.y = element_text(color = "#000000", size = 10))

county_m %>% 
  group_by(date) %>% 
  mutate(unsen_male = sum(unsen_male), unsen_female = sum(unsen_female),
         sen_male = sum(sen_male), sen_female = sum(sen_female), total = sum(total)) %>% 
  mutate(unsen = unsen_male + unsen_female, sen = sen_male + sen_female, ratio = unsen / sen) %>%
  select(date, unsen, sen, ratio) %>% 
  unique() %>% 
  arrange(date) %>% 
  ggplot(data = ., mapping = aes(x = date, y = ratio)) +
  geom_vline(xintercept = as.Date("2011-01-01"), linetype = "dotted") +
  geom_vline(xintercept = as.Date("2012-01-01"), linetype = "dotted") +
  geom_vline(xintercept = as.Date("2014-01-01"), linetype = "dotted") +
  geom_vline(xintercept = as.Date("2016-01-01"), linetype = "dotted") +
  geom_line() +
  labs(x = "Year", y = "Ratio of Unsentenced to Sentenced") +
  theme_classic() +
  theme(axis.text.x = element_text(color = "#000000", size = 10),
        axis.text.y = element_text(color = "#000000", size = 10))
```

# Length of Stay

```{r length_of_stay_data}
length_of_stay <- county_q %>% 
  filter(year > 2001) %>% 
  select(county, date, pretrial_release, sentenced_release) %>% 
  na.omit() %>% 
  arrange(date)
```

```{r length_of_stay_missingness}
# identify counties with length of stay missingness
pretrial_missingness <- county_q %>% 
  filter(year > 2001) %>% 
  group_by(county) %>%  
  count(is.na(pretrial_release)) %>% 
  mutate(proportion = n / sum(n)) %>% 
  filter(`is.na(pretrial_release)`) %>% 
  arrange(county) %>% 
  filter(proportion < 0.25)

sentenced_missingness <- county_q %>% 
  filter(year > 2001) %>% 
  group_by(county) %>% 
  count(is.na(sentenced_release)) %>% 
  mutate(proportion = n / sum(n)) %>% 
  filter(`is.na(sentenced_release)`) %>% 
  arrange(county) %>% 
  filter(proportion < 0.25)

missingness <- intersect(pretrial_missingness$county, sentenced_missingness$county)

# identify differences in length of stay filtering by counties without missingness
length_of_stay_no_filter <- length_of_stay %>% 
  group_by(date) %>% 
  mutate(pretrial_no_filter = median(pretrial_release), sentenced_no_filter = median(sentenced_release)) %>% 
  select(date, pretrial_no_filter, sentenced_no_filter) %>% 
  unique()

length_of_stay_filter <- length_of_stay %>% 
  filter(county %in% missingness) %>%
  group_by(date) %>% 
  mutate(pretrial_filter = median(pretrial_release), sentenced_filter = median(sentenced_release)) %>% 
  select(date, pretrial_filter, sentenced_filter) %>% 
  unique()

missingness_comparison <- bind_cols(length_of_stay_no_filter, length_of_stay_filter[,2:3]) 

missingness_comparison <- missingness_comparison %>% 
  mutate(pretrial_diff = pretrial_no_filter - pretrial_filter,
         sentenced_diff = sentenced_no_filter - sentenced_filter)
  # group_by(year) %>% 
  # mutate(pretrial_diff = mean(pretrial_diff), sentenced_diff = mean(sentenced_diff)) %>% 
  # select(year, pretrial_diff, sentenced_diff) %>% 
  # unique()

# missingness_comparison$year <- as.factor(missingness_comparison$year)

ggplot(data = missingness_comparison, mapping = aes(x = date, y = pretrial_diff)) +
  geom_boxplot(mapping = aes(group = cut_width(year(date), 1))) +
  labs(x = "Date", y = "Difference") +
  theme_classic() +
  theme(axis.text.x = element_text(color = "#000000", size = 10),
        axis.text.y = element_text(color = "#000000", size = 10))

ggplot(data = missingness_comparison, mapping = aes(x = date, y = sentenced_diff)) +
  geom_boxplot(mapping = aes(group = cut_width(year(date), 1))) +
  labs(x = "Date", y = "Difference") +
  theme_classic() +
  theme(axis.text.x = element_text(color = "#000000", size = 10),
        axis.text.y = element_text(color = "#000000", size = 10))

# median(length_of_stay_no_filter$pretrial_release - length_of_stay_filter$pretrial_release)
# median(length_of_stay_no_filter$sentenced_release - length_of_stay_filter$sentenced_release)
```

```{r length_of_stay_analysis}
# calculate changes in length of stay 1, 3, and 5 years after realignment
length_of_stay_one_yr <- length_of_stay %>% 
  filter(county == "Colusa County" | county == "Fresno County" | county == "Mariposa County",
         year(date) == 2011 | year(date) == 2012, month(date) == 1) %>% 
  arrange(date) %>% 
  group_by(county) %>% 
  mutate(pretrial_change = (pretrial_release / lag(pretrial_release) - 1) * 100,
         sentenced_change = (sentenced_release / lag(sentenced_release) - 1) * 100) %>% 
  filter(year(date) == 2012)

length_of_stay_three_yr <- length_of_stay %>% 
  filter(county == "Colusa County" | county == "Fresno County" | county == "Mariposa County",
         year(date) == 2011 | year(date) == 2014, month(date) == 1) %>% 
  arrange(date) %>% 
  group_by(county) %>% 
  mutate(pretrial_change = (pretrial_release / lag(pretrial_release) - 1) * 100,
         sentenced_change = (sentenced_release / lag(sentenced_release) - 1) * 100) %>% 
  filter(year(date) == 2014)

length_of_stay_five_yr <- length_of_stay %>% 
  filter(county == "Colusa County" | county == "Fresno County" | county == "Mariposa County",
         year(date) == 2011 | year(date) == 2016, month(date) == 1) %>% 
  arrange(date) %>% 
  group_by(county) %>% 
  mutate(pretrial_change = (pretrial_release / lag(pretrial_release) - 1) * 100,
         sentenced_change = (sentenced_release / lag(sentenced_release) - 1) * 100) %>% 
  filter(year(date) == 2016)

realignment_length_of_stay <- length_of_stay %>% 
  filter(county == "Colusa County" | county == "Fresno County" | county == "Mariposa County",
         year(date) == 2011 & month(date) == 1) %>% 
  select(county, pretrial_release, sentenced_release) %>% 
  group_by(county) %>% 
  rename(`2011_pretrial` = pretrial_release, `2011_sentenced` = sentenced_release)

realignment_length_of_stay$`2012_pretrial` = length_of_stay_one_yr$pretrial_release
realignment_length_of_stay$`2012_pre_change` = length_of_stay_one_yr$pretrial_change
realignment_length_of_stay$`2012_sentenced` = length_of_stay_one_yr$sentenced_release
realignment_length_of_stay$`2012_sen_change` = length_of_stay_one_yr$sentenced_change

realignment_length_of_stay$`2014_pretrial` = length_of_stay_three_yr$pretrial_release
realignment_length_of_stay$`2014_pre_change` = length_of_stay_three_yr$pretrial_change
realignment_length_of_stay$`2014_sentenced` = length_of_stay_three_yr$sentenced_release
realignment_length_of_stay$`2014_sen_change` = length_of_stay_three_yr$sentenced_change

realignment_length_of_stay$`2016_pretrial` = length_of_stay_five_yr$pretrial_release
realignment_length_of_stay$`2016_pre_change` = length_of_stay_five_yr$pretrial_change
realignment_length_of_stay$`2016_sentenced` = length_of_stay_five_yr$sentenced_release
realignment_length_of_stay$`2016_sen_change` = length_of_stay_five_yr$sentenced_change

quantile(realignment_length_of_stay$`2012_pre_change`, c(0.25, 0.5, 0.75))
quantile(realignment_length_of_stay$`2012_sen_change`, c(0.25, 0.5, 0.75))
quantile(realignment_length_of_stay$`2014_pre_change`, c(0.25, 0.5, 0.75))
quantile(realignment_length_of_stay$`2014_sen_change`, c(0.25, 0.5, 0.75))
quantile(realignment_length_of_stay$`2016_pre_change`, c(0.25, 0.5, 0.75))
quantile(realignment_length_of_stay$`2016_sen_change`, c(0.25, 0.5, 0.75))
```

```{r length_of_stay_modeling}

```

```{r length_of_stay_viz}
length_of_stay %>% 
  group_by(date) %>% 
  mutate(pretrial_release = median(pretrial_release), sentenced_release = median(sentenced_release)) %>% 
  unique() %>% 
  ggplot(data = ., mapping = aes(x = date, group = 1)) +
  geom_line(mapping = aes(y = pretrial_release, linetype = "solid")) +
  geom_line(mapping = aes(y = sentenced_release, linetype = "dotted")) +
  labs(x = "Year", y = "Median Lengths of Stay") +
  scale_linetype_manual(name = "Sentence Type",
                        values = c("solid", "dotted"), labels = c("Sentenced", "Pretrial")) +
  theme_classic() +
  theme(axis.text.x = element_text(color = "#000000", size = 10),
        axis.text.y = element_text(color = "#000000", size = 10))

county_q %>% 
  filter(year > 2001, county == "Los Angeles County" | county == "San Francisco County") %>% 
  select(county, date, pretrial_release, sentenced_release) %>% 
  mutate(county = case_when(county == "Los Angeles County" ~ "la", county == "San Francisco County" ~ "sf"),
         row = row_number()) %>% 
  pivot_wider(names_from = county, values_from = c(pretrial_release, sentenced_release)) %>% 
  select(-row) %>% 
  group_by(date) %>% 
  fill(everything(), .direction = "down") %>%
  fill(everything(), .direction = "up") %>% 
  unique() %>% 
  ggplot(data = ., mapping = aes(x = date, group = 1)) +
  geom_line(mapping = aes(y = pretrial_release_la, color = "la", linetype = "solid")) +
  geom_line(mapping = aes(y = pretrial_release_sf, color = "sf", linetype = "solid")) +
  geom_line(mapping = aes(y = sentenced_release_la, color = "la", linetype = "dotted")) +
  geom_line(mapping = aes(y = sentenced_release_sf, color = "sf", linetype = "dotted")) +
  labs(x = "Year", y = "Average Lengths of Stay") +
  scale_color_discrete(name = "County", breaks = c("la", "sf"), labels = c("Los Angeles", "San Francisco")) +
  scale_linetype_manual(name = "Sentence Type",
                        values = c("solid", "dotted"), labels = c("Sentenced", "Unsentenced")) +
  theme_classic() +
  theme(axis.text.x = element_text(color = "#000000", size = 10),
        axis.text.y = element_text(color = "#000000", size = 10))
```

# Realignment

```{r realignment_data}
realignment_population
realignment_length_of_stay
```

```{r realignment_modeling}

```

```{r realignment_viz}
county_m %>% 
  filter(county == "San Diego County") %>% 
  select(date, unsen_male, unsen_female, sen_male, sen_female, total) %>% 
  group_by(date) %>% 
  mutate(unsen_male = sum(unsen_male), unsen_female = sum(unsen_female),
         sen_male = sum(sen_male), sen_female = sum(sen_female), total = sum(total)) %>% 
  unique() %>% 
  arrange(date) %>% 
  ggplot(data = ., mapping = aes(x = date, group = 1)) +
  geom_line(mapping = aes(y = sen_male, color = "male", linetype = "solid")) +
  geom_line(mapping = aes(y = sen_female, color = "female", linetype = "solid")) +
  geom_line(mapping = aes(y = unsen_male, color = "male", linetype = "dotted")) +
  geom_line(mapping = aes(y = unsen_female, color = "female", linetype = "dotted")) +
  labs(x = "Year", y = "Average Daily Populations") +
  scale_color_discrete(name = "Gender", breaks = c("male", "female"), labels = c("Male", "Female")) +
  scale_linetype_manual(name = "Sentence Type",
                        values = c("solid", "dotted"), labels = c("Sentenced", "Unsentenced")) +
  theme_classic() +
  theme(axis.text.x = element_text(color = "#000000", size = 10),
        axis.text.y = element_text(color = "#000000", size = 10), legend.position = "none")

length_of_stay %>% 
  filter(county == "San Diego County") %>% 
  ggplot(data = ., mapping = aes(x = date, group = 1)) +
  geom_line(mapping = aes(y = pretrial_release, linetype = "solid")) +
  geom_line(mapping = aes(y = sentenced_release, linetype = "dotted")) +
  labs(x = "Year", y = "Average Lengths of Stay") +
  scale_linetype_manual(name = "Sentence Type",
                        values = c("solid", "dotted"), labels = c("Sentenced", "Pretrial")) +
  theme_classic() +
  theme(axis.text.x = element_text(color = "#000000", size = 10),
        axis.text.y = element_text(color = "#000000", size = 10), legend.position = "none")
```